version: '2'
services:
    planning-app:
        image: planning
        external_links:
            - planning-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/planning
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    planning-postgresql:
        extends:
            file: postgresql.yml
            service: planning-postgresql
